version: "3"

services:
  web:
    container_name: bookExchangeBackEndB
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3500"
    links:
      - mongo
  mongo:
    container_name: mongoBookExchangeBBDD
    image: mongo
    ports:
      - "27050:27017"